### PR TITLE
This Closes #24 - Update README.md

### LINKED ISSUE #24: Keys combination not working
image

Just installed it but I can't make it by no mean work. Keys combinations ton working (tried all).

Using latest VSCode and latest OSx.

### PR DESCRIPTION
**Pull request by vapits**
Make keys combination on readme more understandable

### CODE REVIEW

**Comment by joelday** [comment]
@vapits Actually, can you change these to "Hold ? and then press ?"

**Comment by vapits** [comment]
@joelday actually i thinked about that but I think it's not correct because it's like a combination. Like Hold A and then pres B then the meaning is press A + B ;)

**Comment by joelday** [comment]
"While holding ?, press ?"

**Comment by vapits** [comment]
The same, but still is a personal opinion, you can edit it as you'd love ;)

**Pull request merged**
